### ISSUE TITLE
Error before 'Build Model'

### ISSUE THREAD

**Issue by pyangnju** [ajay6763/LitMod2D_2.0_package_dist_users#27]
After I select folder and click 'OK' button, the 'build model' window did not appear.
![image](https://user-images.githubusercontent.com/103311243/162566293-027446a3-109b-4f9e-a967-2aecb02bf887.png)

The error code screenshot is below:
![image](https://user-images.githubusercontent.com/103311243/162566460-879ab7a6-37fb-418a-a399-9b533dd84bd7.png)

Looking forward to get solution from anyone!

Thanks!

**Comment by pyangnju** [comment]
I will show the complete Error code below：

> Warning: Unable to import the wx backend for pyface due to traceback: Traceback (most recent call last):
	  File "D:\Anaconda\envs\LitMod\lib\site-packages\pyface\toolkit.py", line 49, in _init_toolkit
	    be = import_toolkit(tk)
	  File "D:\Anaconda\envs\LitMod\lib\site-packages\pyface\toolkit.py", line 31, in import_toolkit
	    __import__(be + 'init')
	  File "D:\Anaconda\envs\LitMod\lib\site-packages\pyface\ui\wx\init.py", line 14, in <module>
	    import wx
	ImportError: No module named wx

> Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Anaconda\envs\LitMod\lib\lib-tk\Tkinter.py", line 1547, in __call__
    return self.func(*args)
  File "D:/���/LithMod_2.0/TEST/GUI/main.py", line 60, in <lambda>
    command=lambda:my_lib.build_model(litmod_path))
  File "D:\���\LithMod_2.0\TEST\GUI\my_lib.py", line 2588, in build_model
    fig = plt.figure(0)
  File "D:\Anaconda\envs\LitMod\lib\site-packages\matplotlib\pyplot.py", line 535, in figure
    **kwargs)
  File "D:\Anaconda\envs\LitMod\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 44, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "D:\Anaconda\envs\LitMod\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 51, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "D:\Anaconda\envs\LitMod\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 242, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "D:\Anaconda\envs\LitMod\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 66, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)
  File "D:\Anaconda\envs\LitMod\lib\site-packages\matplotlib\backends\backend_qt5.py", line 240, in __init__
    super(FigureCanvasQT, self).__init__(figure=figure)
AttributeError: 'figure()' is not a Qt property or a signal

My OS is Windows. I checked  the packages in file requirements.txt and all the packages were installed successfully except 'vtk==8.1.2'.  It seems that the version vtk > 8.0.0 is not compatible in Python 2.7. So I am not sure whether this problem cause the failure.

**Comment by pyangnju** [comment]
Now I make sure that the problem is the Qt4 and QT5 backends being mixed up. It is similar in  #6420. So I add the code 

> import matplotlib
matplotlib.use('Qt5Agg')
import matplotlib.pyplot as plt

to the main.py in GUI and then it works well. 
At least the GUI is shown now hah.

**Comment by ajay6763** [comment]
Thanks @pyangnju for figuring it out. I labelled it as a good first issue for the Windows users (I figured it from your attached figure and appearance of the Tk window, correct me if  I am wrong) who want to have a standalone installation without the docker. I guess you made specified additions to the main.py and places where Matplotlib is imported?
